export const SET_INIT_APP = "app/SET_INIT_APP";
export const SET_EXPO_PUSH_TOKEN = "app/SET_EXPO_PUSH_TOKEN";
export const SET_SUBSCRIBER_ID = "app/SET_SUBSCRIBER_ID";
export const SET_DEVICE_ID = "app/SET_DEVICE_ID";
export const SET_NOTIFICATIONS = "app/SET_NOTIFICATIONS";
export const SET_NEW_NOTIFICATIONS_COUNT = "app/SET_NEW_NOTIFICATIONS_COUNT";
export const CLEAR_HISTOTRY_APPOINTMENTS_ERROR =
  "app/CLEAR_HISTOTRY_APPOINTMENTS_ERROR";
export const SET_HISTOTRY_APPOINTMENTS_ERROR =
  "app/SET_HISTOTRY_APPOINTMENTS_ERROR";

export const SET_USER_DATA = "user/SET_USER_DATA";
export const SET_USER_PROFILE = "user/SET_USER_PROFILE";
export const SET_USER_FAMILY = "user/SET_USER_FAMILY";
export const SET_USER_ERROR = "user/SET_ERROR";
export const SET_USER_LOADING = "user/SET_USER_LOADING";
export const SET_SICK_LIST_INFO = "user/SET_SICK_LIST_INFO";
export const SET_SICK_LIST_ERROR = "user/SET_SICK_LIST_ERROR";
export const CLEAR_SICK_LIST_ERROR = "user/CLEAR_SICK_LIST_ERROR";
export const SET_MEDICAL_DOC_TYPES = "user/SET_MEDICAL_DOC_TYPES";
export const CLEAR_SICK_LIST_INFO = "user/CLEAR_SICK_LIST_INFO";
export const CLEAR_USER_ERROR = "user/CLEAR_USER_ERROR";
export const SET_AUTH_REQUEST = "user/SET_AUTH_REQUEST";
export const CLEAR_AUTH_REQUEST = "user/CLEAR_AUTH_REQUEST";
export const SET_VISIBLE_CONFIRM_CODE_FIELD =
  "user/SET_VISIBLE_CONFIRM_CODE_FIELD";

export const SET_ALL_MO = "hospitals/SET_ALL_MO";
export const SET_HOSPITALS_FOR_APPOINTMENT =
  "hospitals/SET_HOSPITALS_FOR_APPOINTMENT";
export const SET_ALL_HOSPITALS = "hospitals/SET_ALL_HOSPITALS";
export const SET_HOSPITALS_LOADING = "hospitals/SET_HOSPITALS_LOADING";
export const SET_HOSPITALS_ERROR = "hospitals/SET_HOSPITALS_ERROR";
export const CLEAR_HOSPITALS_ERROR = "hospitals/CLEAR_HOSPITALS_ERROR";
export const CLEAR_ALL_HOSPITALS = "hospitals/CLEAR_ALL_HOSPITALS";
export const CLEAR_HOSPITALS_FOR_APPOINTMENT =
  "hospitals/CLEAR_HOSPITALS_FOR_APPOINTMENT";
export const CLEAR_ALL_MO = "hospitals/CLEAR_ALL_MO";
export const SET_DATA_LIST_FOR_TIMETABLE =
  "hospitals/SET_DATA_LIST_FOR_TIMETABLE";
export const SET_DOCTORS_LIST_LOADING = "hospitals/SET_DOCTORS_LIST_LOADING";
export const CLEAR_DATA_LIST_FOR_TIMETABLE =
  "hospitals/CLEAR_DATA_LIST_FOR_TIMETABLE";
export const SET_DOCTORS_TIMETABLE = "hospitals/SET_DOCTORS_TIMETABLE";
export const CLEAR_DOCTORS_TIMETABLE = "hospitals/CLEAR_DOCTORS_TIMETABLE";
export const SET_DOCTORS_TIMETABLE_LOADING =
  "hospitals/SET_DOCTORS_TIMETABLE_LOADING";
export const SET_DATA_LIST_FOR_RAITING = "hospitals/SET_DATA_LIST_FOR_RAITING";
export const SET_SCAN_DATA_LIST_FOR_RAITING =
  "hospitals/SET_SCAN_DATA_LIST_FOR_RAITING";
export const SET_DATA_LIST_FOR_RAITING_LOADING =
  "hospitals/SET_DATA_LIST_FOR_RAITING_LOADING";
export const CLEAR_DATA_LIST_FOR_RAITING =
  "hospitals/CLEAR_DATA_LIST_FOR_RAITING";
export const CLEAR_SCAN_DATA_LIST_FOR_RAITING =
  "hospitals/CLEAR_SCAN_DATA_LIST_FOR_RAITING";
export const SET_LIST_OF_WORKINDICATORS =
  "hospitals/SET_LIST_OF_WORKINDICATORS";
export const CLEAR_LIST_OF_WORKINDICATORS =
  "hospitals/CLEAR_LIST_OF_WORKINDICATORS";
export const SET_EVALUATION_RESULT = "hospitals/SET_EVALUATION_RESULT";
export const SET_EVALUATION_RESULT_LOADING =
  "hospitals/SET_EVALUATION_RESULT_LOADING";
export const CLEAR_EVALUATION_RESULT = "hospitals/CLEAR_EVALUATION_RESULT";

export const SET_APPOINTMENT_USER_DATA =
  "appointment/SET_APPOINTMENT_USER_DATA";
export const SET_APPOINTMENT_SHEDULE = "appointment/SET_APPOINTMENT_SHEDULE";
export const CLEAR_APPOINTMENT_SHEDULE =
  "appointment/CLEAR_APPOINTMENT_SHEDULE";
export const CLEAR_APPOINTMENT_USER_DATA =
  "appointment/CLEAR_APPOINTMENT_USER_DATA";
export const SET_APPOINTMENT_ERROR = "appointment/SET_APPOINTMENT_ERROR";
export const CLEAR_APPOINTMENT_ERROR = "appointment/CLEAR_APPOINTMENT_ERROR";
export const SET_APPOINTMENT_PROFILE_SPECS =
  "appointment/SET_APPOINTMENT_PROFILE_SPECS";
export const CLEAR_APPOINTMENT_PROFILE_SPECS =
  "appointment/CLEAR_APPOINTMENT_PROFILE_SPECS";
export const SET_APPOINTMENT_LOADING_USER_DATA =
  "appointment/SET_APPOINTMENT_LOADING_USER_DATA";
export const SET_APPOINTMENT_LOADING_SHEDULE =
  "appointment/SET_APPOINTMENT_LOADING_SHEDULE";
export const SET_APPOINTMENT_LOADING_PROFILE_SPECS =
  "appointment/SET_APPOINTMENT_LOADING_PROFILE_SPECS";
export const SET_HOUSE_CALL_RESULT = "appointment/SET_HOUSE_CALL_RESULT";
export const SET_SAVE_APPOINTMENT_RESULT =
  "appointment/SET_SAVE_APPOINTMENT_RESULT";
export const SET_SAVE_APPOINTMENT_LOADING =
  "appointment/SET_SAVE_APPOINTMENT_LOADING";
export const CLEAR_HOUSE_CALL_RESULT = "appointment/CLEAR_HOUSE_CALL_RESULT";
export const CLEAR_SAVE_APPOINTMENT_RESULT =
  "appointment/SET_SAVE_APPOINTMENT_RESULT";
export const SET_NOTIFICATIONS_ERROR = "appointment/SET_NOTIFICATIONS_ERROR";
export const SET_NOTIFICATIONS_LOADING =
  "appointment/SET_NOTIFICATIONS_LOADING";
export const SET_HISTOTRY_APPOINTMENTS =
  "appointment/SET_HISTOTRY_APPOINTMENTS";

export const SET_MEDICATIONS_LIST = "medications/SET_MEDICATIONS_LIST";
export const SET_MEDICATIONS_MAP_MARKERS =
  "medications/SET_MEDICATIONS_MAP_MARKERS";
export const CLEAR_MEDICATIONS_LIST = "medications/CLEAR_MEDICATIONS_LIST";
export const CLEAR_MEDICATIONS_MAP_MARKERS =
  "medications/CLEAR_MEDICATIONS_MAP_MARKERS";
export const SET_MEDICATIONS_LIST_LOADING =
  "medications/SET_MEDICATIONS_LIST_LOADING";
export const SET_MEDICATIONS_ERROR = "medications/SET_MEDICATIONS_ERROR";
export const CLEAR_MEDICATIONS_ERROR = "medications/CLEAR_MEDICATIONS_ERROR";
