export const SET_INIT_APP = "app/SET_INIT_APP";

export const SET_USER_DATA = "user/SET_USER_DATA";
export const SET_USER_PROFILE = "user/SET_USER_PROFILE";
export const SET_USER_ERROR = "user/SET_ERROR";
export const SET_USER_LOADING = "user/SET_USER_LOADING";
export const SET_SICK_LIST_INFO = "user/SET_SICK_LIST_INFO";
export const SET_MEDICAL_DOC_TYPES = "user/SET_MEDICAL_DOC_TYPES";
export const CLEAR_SICK_LIST_INFO = "user/CLEAR_SICK_LIST_INFO"
export const CLEAR_USER_ERROR = "user/CLEAR_USER_ERROR"

export const SET_ALL_MO = "hospitals/SET_ALL_MO";
export const SET_HOSPITALS_FOR_APPOINTMENT =
  "hospitals/SET_HOSPITALS_FOR_APPOINTMENT";
export const SET_ALL_HOSPITALS = "hospitals/SET_ALL_HOSPITALS";
export const SET_HOSPITALS_LOADING = "hospitals/SET_HOSPITALS_LOADING";
export const SET_HOSPITALS_ERROR = "hospitals/SET_HOSPITALS_ERROR";
export const CLEAR_HOSPITALS_ERROR = "hospitals/CLEAR_HOSPITALS_ERROR";
export const CLEAR_ALL_HOSPITALS = "hospitals/CLEAR_ALL_HOSPITALS";
export const CLEAR_HOSPITALS_FOR_APPOINTMENT =
  "hospitals/CLEAR_HOSPITALS_FOR_APPOINTMENT";
export const CLEAR_ALL_MO = "hospitals/CLEAR_ALL_MO";
export const SET_DATA_LIST_FOR_TIMETABLE = "hospitals/SET_DATA_LIST_FOR_TIMETABLE"
export const SET_DOCTORS_LIST_LOADING = "hospitals/SET_DOCTORS_LIST_LOADING"
export const CLEAR_DATA_LIST_FOR_TIMETABLE = "hospitals/CLEAR_DATA_LIST_FOR_TIMETABLE"
export const SET_DOCTORS_TIMETABLE = "hospitals/SET_DOCTORS_TIMETABLE"
export const CLEAR_DOCTORS_TIMETABLE = "hospitals/CLEAR_DOCTORS_TIMETABLE"
export const SET_DOCTORS_TIMETABLE_LOADING = "hospitals/SET_DOCTORS_TIMETABLE_LOADING"

export const SET_APPOINTMENT_USER_DATA =
  "appointment/SET_APPOINTMENT_USER_DATA";
export const SET_APPOINTMENT_SHEDULE = "appointment/SET_APPOINTMENT_SHEDULE";
export const CLEAR_APPOINTMENT_SHEDULE =
  "appointment/CLEAR_APPOINTMENT_SHEDULE";
export const CLEAR_APPOINTMENT_USER_DATA =
  "appointment/CLEAR_APPOINTMENT_USER_DATA";
export const SET_APPOINTMENT_ERROR = "appointment/SET_APPOINTMENT_ERROR";
export const CLEAR_APPOINTMENT_ERROR = "appointment/CLEAR_APPOINTMENT_ERROR";
export const SET_APPOINTMENT_PROFILE_SPECS =
  "appointment/SET_APPOINTMENT_PROFILE_SPECS";
export const CLEAR_APPOINTMENT_PROFILE_SPECS =
  "appointment/CLEAR_APPOINTMENT_PROFILE_SPECS";
export const SET_APPOINTMENT_LOADING_USER_DATA =
  "appointment/SET_APPOINTMENT_LOADING_USER_DATA";
export const SET_APPOINTMENT_LOADING_SHEDULE =
  "appointment/SET_APPOINTMENT_LOADING_SHEDULE";
export const SET_APPOINTMENT_LOADING_PROFILE_SPECS =
  "appointment/SET_APPOINTMENT_LOADING_PROFILE_SPECS";
